import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 统一的「博客」侧边栏：所有主题分类都在这棵目录树下
 * 每个分类（category）自动从 docs/<dirName> 拉取文章
 */
const sidebars: SidebarsConfig = {
    blogSidebar: [
        'intro',
        {
            type: 'category',
            label: '数据结构与算法',
            collapsed: false,
            items: [{type: 'autogenerated', dirName: 'algorithm'}],
        },
        {
            type: 'category',
            label: 'Java 后端',
            collapsed: false,
            items: [{type: 'autogenerated', dirName: 'backend'}],
        },
        {
            type: 'category',
            label: '计算机课程',
            collapsed: false,
            items: [{type: 'autogenerated', dirName: 'course'}],
        },
        {
            type: 'category',
            label: '面试题',
            collapsed: false,
            items: [{type: 'autogenerated', dirName: 'interview'}],
        },
        {
            type: 'category',
            label: '工具随笔',
            collapsed: false,
            items: [{type: 'autogenerated', dirName: 'tools'}],
        },
    ],
};

export default sidebars;
